stages:
  unzip_dataset:
      cmd: python src/stages/unzip_dataset.py 
      outs:
      - data/${data.train}:
          cache: false
      deps:
      - data/${data.train}.zip
      - src/stages/unzip_dataset.py
      params:
      - data

  train_model:
      cmd: python src/stages/train.py 
      deps:
      - data/${data.train}
      - src/stages/train.py
      outs:
      - ${train.model_path}/${train.model_file}
      params:
      - data
      - train
      metrics:
      - ${reports.root}/dvclive.json:
          cache: false
      plots:
      - ${reports.root}/dvclive/scalars:
          cache: false

  visualise:
      cmd: python src/stages/visualise_embeddings.py
      deps:
      - ${train.model_path}/${train.model_file}
      - src/stages/visualise_embeddings.py
      plots:
      - ${reports.root}/${reports.plots}/embedding.png:
          cache: false
      params:
      - reports