stages:
  unzip_dataset:
    cmd: python src/stages/unzip_dataset.py --params=params.yaml
    deps:
      - src/stages/unzip_dataset.py
      - ${unzip_dataset.data_root}/${unzip_dataset.archive_baseline}
    params:
      - unzip_dataset
    outs:
      - ${unzip_dataset.data_root}/${unzip_dataset.dataset_baseline}:
          cache: false
  preprocess_dataset:
    cmd: python src/stages/preprocess_dataset.py --params=params.yaml
    deps:
      - src/stages/preprocess_dataset.py
      - ${unzip_dataset.data_root}/${unzip_dataset.dataset_baseline}
    params:
      - unzip_dataset
      - preprocess_dataset
    outs:
      - ${unzip_dataset.data_root}/${preprocess_dataset.output_folder}:
          cache: false 
# Split to test and train