data:
  root: data
  index_file: "index.txt"

datasets:
  #  - Benchmark
  # - Dishes
  # - Landmarks
  # - MNIST_exp
  - baseline_130k_128_split
train:
  model_path: "models"
  model_file: "saved_model.pt"
  batch_size: 500
  margin: 10
  lr: 0.001
  scheduler_step_size: 14
  epochs: 18
  embedding_size: 64

reports:
  root: "reports"
  plots: "plots"



  


