data:
  root: data
  dataset_baseline: images_128
  teacher_data: teacher_data
  train: baseline_split

train:
  model_path: "models"
  model_file: "model.pt"
  batch_size: 512
  margin: 5
  lr: 0.001
  epochs: 30
  embedding_size: 64

reports:
  root: "reports"
  plots: "plots"

  


