data:
  root: data
  teacher_data: teacher
  train: baseline_split

teacher_models:
  #  - Benchmark
  - Dishes
  # - Landmarks
  # - MNIST_exp
train:
  model_path: "models"
  model_file: "saved_model.pt"
  batch_size: 500
  margin: 5
  lr: 0.01
  scheduler_step_size: 14
  epochs: 30
  embedding_size: 64

reports:
  root: "reports"
  plots: "plots"



  


