data:
  archive_baseline: archive.zip
  root: data
  dataset_baseline: images_128
  teacher_data: teacher_data
  train_data: teacher_splitted

teacher_models:
  #  - Benchmark
  - Dishes
  # - Landmarks
  # - MNIST_exp
train:
  model_path: "models"
  model_file: "saved_model.pt"
  batch_size: 512
  margin: 5
  lr: 0.01
  scheduler_step_size: 14
  epochs: 50
  embedding_size: 64

reports:
  root: "reports"
  plots: "plots"



  


