data:
  root: data
  index_file: "index.txt"

datasets:
- baseline_kais_apparel

data_preprocessing:
  index_file_folder: data/kaggle_130k

train:
  model_path: "models"
  model_file: "saved_model.pt"
  batch_size: 500
  margin: 10
  lr: 0.001
  scheduler_step_size: 14
  epochs: 18
  embedding_size: 64

reports:
  root: "reports"
  plots: "plots"



  


