[tool.poetry]
name = "google-kaggle"
version = "0.1.0"
description = ""
authors = ["Yury <yury@iterative.ai>"]

[tool.poetry.dependencies]
python = "^3.10"
torch = "^1.12.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
